- name: SSH Remote Deployment to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. INYECTAR CREDENCIALES A LA EC2 (Las 3 líneas mágicas)
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            
            # 2. Ahora la EC2 sí tiene permiso para entrar a tu ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
            
            docker network create casino-network || true
            
            if [ ! "$(docker ps -a -q -f name=casino-db)" ]; then
              docker run -d --name casino-db --network casino-network --restart always \
                -e POSTGRES_DB=casino \
                -e POSTGRES_USER=postgres \
                -e POSTGRES_PASSWORD=postgres \
                postgres:15-alpine
            fi
            
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/casino-backend:latest
            
            docker stop casino-backend-prod || true
            docker rm casino-backend-prod || true
            
            docker run -d --name casino-backend-prod --network casino-network --restart always \
              -p 3000:3000 \
              -e DB_HOST=casino-db \
              -e DB_USER=postgres \
              -e DB_PASSWORD=postgres \
              -e DB_NAME=casino \
              -e PORT=3000 \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/casino-backend:latest